CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Discriminator" character varying(13) NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" character varying(15) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "DeviceToken" text,
    "Bio" text,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Avatar" text,
    "RoleId" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SubCategory" (
    "SubCategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_SubCategory" PRIMARY KEY ("SubCategoryId"),
    CONSTRAINT "FK_SubCategory_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "Token" character varying(250) NOT NULL,
    "UserId" text NOT NULL,
    "ExpiresOnUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Registerations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CrNumber" character varying(15) NOT NULL,
    "EntityName" text NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "ImagePath" text NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Registerations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Registerations_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Requests" (
    "RequestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "State" integer NOT NULL,
    "RejectionReason" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("RequestId"),
    CONSTRAINT "FK_Requests_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PlaceDetails" (
    "PlaceDetailsId" integer NOT NULL,
    "PlaceName" character varying(255) NOT NULL,
    "Description" text,
    "WorkingHours" text,
    "Type" integer NOT NULL,
    "City" integer NOT NULL,
    "Address" character varying(250),
    "Email" character varying(250),
    "CategoryId" integer NOT NULL,
    "RequestId" integer NOT NULL,
    "CommericalRegisterationId" integer NOT NULL,
    CONSTRAINT "PK_PlaceDetails" PRIMARY KEY ("PlaceDetailsId"),
    CONSTRAINT "FK_PlaceDetails_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId"),
    CONSTRAINT "FK_PlaceDetails_Registerations_CommericalRegisterationId" FOREIGN KEY ("CommericalRegisterationId") REFERENCES "Registerations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaceDetails_Requests_PlaceDetailsId" FOREIGN KEY ("PlaceDetailsId") REFERENCES "Requests" ("RequestId") ON DELETE CASCADE
);

CREATE TABLE "PhoneNumbers" (
    "Number" character varying(10) NOT NULL,
    "PlaceDetailsId" integer NOT NULL,
    CONSTRAINT "PK_PhoneNumbers" PRIMARY KEY ("Number"),
    CONSTRAINT "FK_PhoneNumbers_PlaceDetails_PlaceDetailsId" FOREIGN KEY ("PlaceDetailsId") REFERENCES "PlaceDetails" ("PlaceDetailsId")
);

CREATE TABLE "PlaceImages" (
    "PlaceImageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImageUrl" text NOT NULL,
    "PlaceDetailsId" integer NOT NULL,
    CONSTRAINT "PK_PlaceImages" PRIMARY KEY ("PlaceImageId"),
    CONSTRAINT "FK_PlaceImages_PlaceDetails_PlaceDetailsId" FOREIGN KEY ("PlaceDetailsId") REFERENCES "PlaceDetails" ("PlaceDetailsId") ON DELETE CASCADE
);

CREATE TABLE "Places" (
    "PlaceId" integer GENERATED BY DEFAULT AS IDENTITY,
    "State" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RequestId" integer NOT NULL,
    "PlaceDetailsId" integer NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Places" PRIMARY KEY ("PlaceId"),
    CONSTRAINT "FK_Places_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Places_PlaceDetails_PlaceDetailsId" FOREIGN KEY ("PlaceDetailsId") REFERENCES "PlaceDetails" ("PlaceDetailsId") ON DELETE CASCADE,
    CONSTRAINT "FK_Places_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("RequestId") ON DELETE CASCADE
);

CREATE TABLE "Favourites" (
    "IdentityUserId" text NOT NULL,
    "PlaceId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Favourites" PRIMARY KEY ("IdentityUserId", "PlaceId"),
    CONSTRAINT "FK_Favourites_AspNetUsers_IdentityUserId" FOREIGN KEY ("IdentityUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Favourites_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE
);

CREATE TABLE "Rates" (
    "RateId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RateValue" smallint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Note" text,
    "PlaceId" integer NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Rates" PRIMARY KEY ("RateId"),
    CONSTRAINT "FK_Rates_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Rates_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "IX_AspNetRoles_Name" ON "AspNetRoles" ("Name");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_Email" ON "AspNetUsers" ("Email");

CREATE INDEX "IX_AspNetUsers_RoleId" ON "AspNetUsers" ("RoleId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Categories_CategoryName" ON "Categories" ("CategoryName");

CREATE INDEX "IX_Favourites_PlaceId" ON "Favourites" ("PlaceId");

CREATE INDEX "IX_PhoneNumbers_PlaceDetailsId" ON "PhoneNumbers" ("PlaceDetailsId");

CREATE INDEX "IX_PlaceDetails_CategoryId" ON "PlaceDetails" ("CategoryId");

CREATE INDEX "IX_PlaceDetails_CommericalRegisterationId" ON "PlaceDetails" ("CommericalRegisterationId");

CREATE UNIQUE INDEX "IX_PlaceDetails_Email" ON "PlaceDetails" ("Email");

CREATE INDEX "IX_PlaceImages_PlaceDetailsId" ON "PlaceImages" ("PlaceDetailsId");

CREATE UNIQUE INDEX "IX_Places_PlaceDetailsId" ON "Places" ("PlaceDetailsId");

CREATE UNIQUE INDEX "IX_Places_RequestId" ON "Places" ("RequestId");

CREATE INDEX "IX_Places_UserId" ON "Places" ("UserId");

CREATE INDEX "IX_Rates_PlaceId" ON "Rates" ("PlaceId");

CREATE INDEX "IX_Rates_UserId" ON "Rates" ("UserId");

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_Registerations_UserId" ON "Registerations" ("UserId");

CREATE INDEX "IX_Requests_UserId" ON "Requests" ("UserId");

CREATE INDEX "IX_SubCategory_CategoryId" ON "SubCategory" ("CategoryId");

CREATE UNIQUE INDEX "IX_SubCategory_Name" ON "SubCategory" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225022307_Initial', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Categories" ALTER COLUMN "CategoryName" TYPE character varying(150);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225195247_CategoryName Column size from 15 to 150', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "PlaceDetails" ALTER COLUMN "Type" TYPE text;

ALTER TABLE "PlaceDetails" ADD "SubCategoryId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_PlaceDetails_SubCategoryId" ON "PlaceDetails" ("SubCategoryId");

ALTER TABLE "PlaceDetails" ADD CONSTRAINT "FK_PlaceDetails_SubCategory_SubCategoryId" FOREIGN KEY ("SubCategoryId") REFERENCES "SubCategory" ("SubCategoryId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226000930_added_Relation_SubCategory_PlaceDetails', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "PlaceDetails" ALTER COLUMN "CategoryId" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260303041223_SubCategory_Category_RelationShip_Fixed', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "PhoneNumbers" DROP CONSTRAINT "FK_PhoneNumbers_PlaceDetails_PlaceDetailsId";

ALTER TABLE "PlaceImages" DROP CONSTRAINT "FK_PlaceImages_PlaceDetails_PlaceDetailsId";

ALTER TABLE "Places" DROP CONSTRAINT "FK_Places_PlaceDetails_PlaceDetailsId";

ALTER TABLE "Places" DROP CONSTRAINT "FK_Places_Requests_RequestId";

DROP TABLE "PlaceDetails";

DROP INDEX "IX_Places_PlaceDetailsId";

DROP INDEX "IX_Places_RequestId";

ALTER TABLE "Places" RENAME COLUMN "PlaceDetailsId" TO "SubCategoryId";

ALTER TABLE "PlaceImages" RENAME COLUMN "PlaceDetailsId" TO "PlaceId";

ALTER INDEX "IX_PlaceImages_PlaceDetailsId" RENAME TO "IX_PlaceImages_PlaceId";

ALTER TABLE "PhoneNumbers" RENAME COLUMN "PlaceDetailsId" TO "PlaceId";

ALTER INDEX "IX_PhoneNumbers_PlaceDetailsId" RENAME TO "IX_PhoneNumbers_PlaceId";

ALTER TABLE "Places" ALTER COLUMN "PlaceId" DROP IDENTITY;

ALTER TABLE "Places" ADD "Address" text;

ALTER TABLE "Places" ADD "CategoryId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Places" ADD "City" integer NOT NULL DEFAULT 0;

ALTER TABLE "Places" ADD "ClosingTime" interval;

ALTER TABLE "Places" ADD "CommericalRegisterationId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Places" ADD "Description" text;

ALTER TABLE "Places" ADD "Email" text;

ALTER TABLE "Places" ADD "Latitude" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Places" ADD "Longitude" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Places" ADD "NearestLandmark" text NOT NULL DEFAULT '';

ALTER TABLE "Places" ADD "OpeningTime" interval;

ALTER TABLE "Places" ADD "PlaceName" text NOT NULL DEFAULT '';

ALTER TABLE "Places" ADD "StreetName" text NOT NULL DEFAULT '';

ALTER TABLE "Places" ADD "Type" text NOT NULL DEFAULT '';

ALTER TABLE "Places" ADD "WorkingHours" text NOT NULL DEFAULT '';

ALTER TABLE "Categories" ADD "CategoryIcon" text;

CREATE INDEX "IX_Places_CategoryId" ON "Places" ("CategoryId");

CREATE INDEX "IX_Places_CommericalRegisterationId" ON "Places" ("CommericalRegisterationId");

CREATE INDEX "IX_Places_SubCategoryId" ON "Places" ("SubCategoryId");

ALTER TABLE "PhoneNumbers" ADD CONSTRAINT "FK_PhoneNumbers_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE;

ALTER TABLE "PlaceImages" ADD CONSTRAINT "FK_PlaceImages_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE;

ALTER TABLE "Places" ADD CONSTRAINT "FK_Places_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE;

ALTER TABLE "Places" ADD CONSTRAINT "FK_Places_Registerations_CommericalRegisterationId" FOREIGN KEY ("CommericalRegisterationId") REFERENCES "Registerations" ("Id") ON DELETE CASCADE;

ALTER TABLE "Places" ADD CONSTRAINT "FK_Places_Requests_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Requests" ("RequestId") ON DELETE CASCADE;

ALTER TABLE "Places" ADD CONSTRAINT "FK_Places_SubCategory_SubCategoryId" FOREIGN KEY ("SubCategoryId") REFERENCES "SubCategory" ("SubCategoryId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260307194517_FixPhoneNumberRelationship', '10.0.3');

COMMIT;

